### ISSUE TITLE
Set Up Initial HTML and CSS using Tailwind CSS framework

### ISSUE THREAD

**Issue by zachary-levin** [MoHarris23/foodfacts#1]
**Description:**
- Set up initial HTML for application based on wireframe
- Utilize Tailwind CSS framework to create appearance of the page.

**After MVP:**
- Add flex to application to accommodate different devices

**Comment by Nickus1028** [comment]
I would install the VS Code extension "Tailwind CSS Intellisense".

**Comment by zachary-levin** [comment]
Need to add flex to elements after MVP is done, but currently finished setting up HTML and CSS to match the mockup
